@call .\script_const.bat

::
if not exist %SLN_PATH%\%SLN_NAME%.sln (
    exit /B 0
)
dotnet build -o %SLN_BIN% -c %SLN_CONFIGURATION% %SLN_PATH%


::
if exist %PRJ_PATH_COPYTO_UTILS% xcopy /Y %SLN_BIN%\%PRJ_NAME_UTILS%.dll %PRJ_PATH_COPYTO_UTILS%
if exist %PRJ_PATH_COPYTO_UTILS% xcopy /Y %SLN_BIN%\%PRJ_NAME_UTILS%.pdb %PRJ_PATH_COPYTO_UTILS%


::
if exist %PRJ_PATH_COPYTO_ARTIST% xcopy /Y %SLN_BIN%\%PRJ_NAME_ARTIST%.dll %PRJ_PATH_COPYTO_ARTIST%
if exist %PRJ_PATH_COPYTO_ARTIST% xcopy /Y %SLN_BIN%\%PRJ_NAME_ARTIST%.pdb %PRJ_PATH_COPYTO_ARTIST%


::
if exist %PRJ_PATH_COPYTO_SAMPLE% xcopy /Y %SLN_BIN%\%PRJ_NAME_SAMPLE%.dll %PRJ_PATH_COPYTO_SAMPLE%
if exist %PRJ_PATH_COPYTO_SAMPLE% xcopy /Y %SLN_BIN%\%PRJ_NAME_SAMPLE%.pdb %PRJ_PATH_COPYTO_SAMPLE%


::
if exist %PRJ_PATH_COPYTO_XLS2LUA% xcopy /Y %SLN_BIN%\%PRJ_NAME_XLS2LUA%.dll %PRJ_PATH_COPYTO_XLS2LUA%
if exist %PRJ_PATH_COPYTO_XLS2LUA% xcopy /Y %SLN_BIN%\%PRJ_NAME_XLS2LUA%.pdb %PRJ_PATH_COPYTO_XLS2LUA%
